name: build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model:
          - Shelly1
          - Shelly1L
          - Shelly1PM
          - Shelly25
          - Shelly2
          - ShellyI3
          - ShellyPlug
          - ShellyPlugS
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install mos build tool
        run: |
          sudo add-apt-repository ppa:mongoose-os/mos -y
          sudo apt -q install mos -y
      - name: Build project
        run: make ${{ matrix.model }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.model }}
          # path: build_${{ matrix.model }}/objs/fw_temp
          path: build_${{ matrix.model }}/fw.zip
          if-no-files-found: error
      - run: md5sum build_${{ matrix.model }}/fw.zip
